---
   - name: Install python-software-properties
     apt:
       name=python-software-properties
       state=present
       update_cache=yes
   - name: Add java 8 ppa repo
     apt_repository:
      repo='ppa:webupd8team/java'
      state=present
   - name: Accept Java 8 License
     debconf:
      name='oracle-java8-installer'
      question='shared/accepted-oracle-license-v1-1'
      value='true'
      vtype='select'
   - name: Install Java 8 package
     apt:
       name=oracle-java8-installer update_cache=yes state=present
